spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.209.17:3306/weixin_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  返回前端的对象属性值不等于null的
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell